services:
  java_app:
    container_name: java_app
    image: back-java-app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://java_db:3306/emprendevsb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: mariadb:10.4.32
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=emprendevsb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
